---
version: 2
jobs:
  build:
    docker:
    - image: suzukishunsuke/go-ci:0.1.0-0
    working_directory: /go/src/github.com/suzuki-shunsuke/akoi
    steps:
    - checkout
    - run: npm i
    - run: dep ensure
    - run: bash script/commitlint-circleci.sh
    - run: gometalinter ./...
    - run: bash script/codecov-test.sh
    - run: bash <(curl -s https://codecov.io/bash)
    - run: bash script/release.sh
workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
